In [1]:
import fitz #pymupdf
import os
import pandas as pd

In [2]:
def extract_text(pdf_path):
    text = ""
    with fitz.open(pdf_path) as doc:
        for page in doc:
            text +=page.get_text("text")+"\n"
    return text.strip()

In [3]:
cv_folder= "D:\downloads\cv"
cv_texts=[]

#loop through the folder
for filename in os.listdir(cv_folder):
    if filename.endswith('.pdf'):
        pdf_path = os.path.join(cv_folder, filename)
        text = extract_text(pdf_path)
    cv_texts.append({'filename':filename, "cv_text":text})
df_cvs= pd.DataFrame(cv_texts)

In [5]:
df_cvs

             filename                                            cv_text
0  Safia_Hamdy-88.pdf  Safia Hamdy Abdelhamid\nData Scientist\nH +201...

In [6]:
from docx import  Document
def extract_text_docs(docx_path):
    doc = Document(docx_path)
    return "\n".join([para.text for para in doc.paragraphs]).strip()

In [8]:
cv_folder= "D:\\downloads\\archive (2)\\Resumes"
docx_texts=[]

#loop through the folder
for filename in os.listdir(cv_folder):
    if filename.endswith('.docx'):
        pdf_path = os.path.join(cv_folder, filename)
        text = extract_text(pdf_path)
    docx_texts.append({'filename':filename, "cv_text":text})
df_cv= pd.DataFrame(docx_texts)

In [9]:
df_cv

,filename,cv_text
0,Abiral_Pandey_Fullstack_Java.docx,Name: Abiral Pandey\nEmail: abiral.pandey88@gm...
1,Achyuth Resume_8.docx,Achyuth\n540-999-8048\nachyuth.java88@gmail.co...
2,Adelina_Erimia_PMP1.docx,"Adelina Erimia, PMP, Six Sigma Green Belt, SMC..."
3,Adhi Gopalam - SM.docx,Adhi Gopalam\nadhigopalam@gmail.com\n281-212-3...
4,AjayKumar.docx,Ajay Kumar (CSM) Email/Skype: ajaydt@gmail.com...
...,...,...
223,Vishnu Java dev.docx,VISHNU J\nEmail to jammigumpulavishnu452@gmail...
224,Vivek Joshi_CV.docx,"Vivek Joshi\nBusiness Analyst\nBellevue, WA\nB..."
225,Vivek.BSA.docx,VIVEK SAGAR\nSr. BUSINESS SYSTEM ANALYST\nPROF...
226,Yohan BSA.docx,"YOHAN\nSr. Business Analyst\nVersatile, effect..."
227,Yugesh_Resume.docx,Yugesh\n+1(515)-650-2459\nyugeshm4@gmail.com\n...

In [10]:
df = pd.concat([df_cv,df_cvs],axis=0, ignore_index=True)

In [11]:
df

,filename,cv_text
0,Abiral_Pandey_Fullstack_Java.docx,Name: Abiral Pandey\nEmail: abiral.pandey88@gm...
1,Achyuth Resume_8.docx,Achyuth\n540-999-8048\nachyuth.java88@gmail.co...
2,Adelina_Erimia_PMP1.docx,"Adelina Erimia, PMP, Six Sigma Green Belt, SMC..."
3,Adhi Gopalam - SM.docx,Adhi Gopalam\nadhigopalam@gmail.com\n281-212-3...
4,AjayKumar.docx,Ajay Kumar (CSM) Email/Skype: ajaydt@gmail.com...
...,...,...
224,Vivek Joshi_CV.docx,"Vivek Joshi\nBusiness Analyst\nBellevue, WA\nB..."
225,Vivek.BSA.docx,VIVEK SAGAR\nSr. BUSINESS SYSTEM ANALYST\nPROF...
226,Yohan BSA.docx,"YOHAN\nSr. Business Analyst\nVersatile, effect..."
227,Yugesh_Resume.docx,Yugesh\n+1(515)-650-2459\nyugeshm4@gmail.com\n...
228,Safia_Hamdy-88.pdf,Safia Hamdy Abdelhamid\nData Scientist\nH +201...

In [12]:
df.to_csv('parsed_cvs.csv')